workingDirectory: /home/wmskaru/public.wmska.ru

vcs:

    svn:
        username: username
        password: password
        url: your-svn-repository

    git:
        username: bilansasha1996
        password: Sasha03081996
        url: https://github.com/bilansasha1996/wms.git

defaultTab: git

tabs:
    git:
        grid:
            rows:
                -
                    - "col-md-3"
                    - "col-md-3"
                    - "col-md-3"
                    - "col-md-3"
        commands:
            pull: git pull origin dev
            status: git status
            diff: git diff
            log: git log

    svn:
            grid:
                rows:
                    -
                        - "col-md-3"
                        - "col-md-3"
                        - "col-md-3"
                        - "col-md-3"

            commands:
                update: svn up --non-interactive --username=${vcs.svn.username} --password=${vcs.svn.password}
                log: svn log --non-interactive --username=${vcs.svn.username} --password=${vcs.svn.password}
                info: svn info --non-interactive
                cleanup:
                    command: svn cleanup --non-interactive
                    description: Если что-то пошло не так, эта команда должна решить все проблемы

    composer:
        grid:
            rows:
                -
                    - "col-md-4"
                    - "col-md-4"
                    - "col-md-4"

        commands:
            update: export COMPOSER_HOME=$(pwd)/.composer && /var/www/1t/data/www/1tdev.client02.prostoy.ru/composer.phar update
            dump-autoload: export COMPOSER_HOME=$(pwd)/.composer && /var/www/1t/data/www/1tdev.client02.prostoy.ru/composer.phar dump-autoload
            info: export COMPOSER_HOME=$(pwd)/.composer && /var/www/1t/data/www/1tdev.client02.prostoy.ru/composer.phar info

    node:
        grid:
            rows:
                -
                    - "col-md-12"
                -
                    - "col-md-6"
                    - "col-md-6"
                -
                    - "col-md-6"
                    - "col-md-6"
                -
                    - "col-md-6"
                    - "col-md-6"
                -
                    - "col-md-6"
                    - "col-md-6"
                -
                    - "col-md-6"
                    - "col-md-6"
                -
                    - "col-md-6"
                    - "col-md-6"
                -
                    - "col-md-6"
                    - "col-md-6"
        commands:
            npm install: npm install

            yarn build: yarn run build
            yarn build-production: yarn run build-production

            yarn build-user: yarn run build-user
            yarn build-user-production: yarn run build-user-production

            yarn build-controller: yarn run build-controller
            yarn build-controller-production: yarn run build-controller-production

            yarn build-operator: yarn run build-operator
            yarn build-operator-production: yarn run build-operator-production

            yarn build-manager: yarn run build-manager
            yarn build-manager-production: yarn run build-manager-production

            yarn build-moderator: yarn run build-moderator
            yarn build-moderator-production: yarn run build-moderator-production

            yarn build-admin: yarn run build-admin
            yarn build-admin-production: yarn run build-admin-production

    artisan:
        grid:
            rows:
                -
                    - "col-md-6"
                    - "col-md-6"
                -
                    - "col-md-4"
                    - "col-md-4"
                    - "col-md-4"
                -
                    - "col-md-3"
                    - "col-md-3"
                    - "col-md-3"
                    - "col-md-3"
                -
                    - "col-md-4"
                    - "col-md-4"
                    - "col-md-4"
                -
                    - "col-md-6"
                    - "col-md-6"
                -
                    - "col-md-4"
                    - "col-md-4"
                    - "col-md-4"

        commands:
            up: php artisan up
            down: php artisan down

            key: php artisan key:generate
            env: cat .env
            routes: php artisan route:list

            migrate: php artisan migrate
            site1t-migrate: php artisan site1t:migrate
            status: php artisan migrate:status
            seed: php artisan db:seed

            clear cache: php artisan cache:clear
            clear config: php artisan config:clear
            storage link: php artisan storage:link

            restart all workers: php artisan queue:restart
            run worker: php artisan queue:work --tries 1

            failed jobs: php artisan queue:failed
            retry all failed jobs: php artisan queue:retry all
            delete all failed jobs: php artisan queue:flush

    tests:
        grid:
            rows:
                -
                    - "col-md-12"
        commands:
            phpunit: vendor/bin/phpunit


    history:
        grid:
            rows:
                -
                    - "col-md-12"
        commands:
            history: cat ${workingDirectory}/public/admin-panel/logs/commands.log
